// <auto-generated />
using Belsis_Parselasyon_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Belsis_Parselasyon_Backend_with_PGgis.Migrations
{
    [DbContext(typeof(ParcelDbContext))]
    [Migration("20220812152110_Migs")]
    partial class Migs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Belsis_Parselasyon_Backend.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("geomectric_features")
                        .HasColumnType("integer");

                    b.Property<string>("il_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Belsis_Parselasyon_Backend.Models.Parcel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("il")
                        .HasColumnType("text");

                    b.Property<string>("ilce")
                        .HasColumnType("text");

                    b.Property<string>("wkt")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
